export const ActionTypes = {
    SET_ROWS: 'SET_ROWS',
    DELETE_ROW: 'DELETE_ROW',
    UPDATE_ROW: 'UPDATE_ROW',
    SET_POSITIONS: 'SET_POSITIONS',
    SET_PRODUCT_CATEGORIES: 'SET_PRODUCT_CATEGORIES',
    SET_PRODUCT_VENDORS: 'SET_PRODUCT_VENDORS'
}
