export const ActionTypes = {
    GET_PRODUCT_CATEGORIES: 'GET_PRODUCT_CATEGORIES',
    GET_PRODUCT_VENDORS: 'GET_PRODUCT_VENDORS',
    GET_SUPPLIERS: 'GET_SUPPLIERS',
    GET_STAFF_POSITIONS: 'GET_STAFF_POSITIONS',
    GET_STAFF: 'GET_STAFF',
    GET_CLIENTS: 'GET_CLIENTS',
    GET_PRODUCTS: 'GET_PRODUCTS'
}
