export const ActionTypes = {
    SET_ROWS: 'SET_ROWS',
    DELETE_ROW: 'DELETE_ROW',
    UPDATE_ROW: 'UPDATE_ROW',
    SET_POSITIONS: 'SET_POSITIONS',
    SET_PRODUCT_CATEGORIES: 'SET_PRODUCT_CATEGORIES',
    SET_PRODUCT_VENDORS: 'SET_PRODUCT_VENDORS',
    SET_PROCUREMENT_PRODUCTS: 'SET_PROCUREMENT_PRODUCTS',
    SET_PROVIDERS: 'SET_PROVIDERS',
    SET_STAFF: 'SET_STAFF',
    SET_PRODUCTS: 'SET_PRODUCTS'
}
